### ISSUE TITLE
API_KEY and API_SECRET

### ISSUE THREAD

**Issue by xeor** [Ludy87/pyxplora_api#11]
I was browsing around trying to debug some login issue and found some key constants that I was curious about defined at https://github.com/Ludy87/pyxplora_api/blob/2.0.104/src/pyxplora_api/const.py

They have been here since the initial commit (https://github.com/Ludy87/pyxplora_api/commit/b490eda9c452e6e0912dfd3f5cd0963f5af92d9f) and I find no traces of them anywhere on github or google..

They seams to be used around https://github.com/Ludy87/pyxplora_api/blob/19acf7c942c0dd95e4ecd2afb97a0b0f0ce13be3/src/pyxplora_api/handler_gql.py#L55-L67, with or without accessToken.. It is also used as a `H-BackDoor-Authorization` header, which is even more confusing..

So what is this? Is it something you got from the xplora people to be able to use the api?
Is it something grabbed from decompiling the app?

And what does the key have access to without the `accessToken`?

**Comment by Ludy87** [comment]
> So what is this? Is it something you got from the xplora people to be able to use the api?
Is it something grabbed from decompiling the app?

My template was here https://github.com/MiGoller/xplora-api.js/blob/main/src/index.ts - then I read the logs via ADB and was able to read the request openly, as well as the entire HEADER of the Inquiry.

> And what does the key have access to without the `accessToken`?

It is used for authentication
 https://github.com/Ludy87/pyxplora_api/blob/255d7c3effa8549aa474af8122dcadbf59311511/src/pyxplora_api/handler_gql.py#L55-L63

**Comment by xeor** [comment]
Thanks for clarifying! I see they use a token as well, however they use another one.. :)

**Comment by Ludy87** [comment]
It's important that it works :D
