### ISSUE TITLE
no message update

### ISSUE THREAD

**Issue by phil1283** [Ludy87/pyxplora_api#122]
**Describe the bug**
After initializing and init of the Xplora class I run a loop:
```
while True:
        print(xplora.getWatchChats(TheRealWuid,0,1))
        time.sleep(30)
```
running the code works fine. I get the last message of the watch.
When the watch sends a message while running the code the newer message is not printed. after a restart of the program the new message is displayed.

**To Reproduce**
Regardless how long the code runs, new message is not displayed.

**Expected behavior**
messages should be refreshed with every `getWatchChats` call like the `getWatchLocate` call. 

Hope I am using it right.

**Comment by Ludy87** [comment]
```python
from time import sleep

from src.pyxplora_api import pyxplora_api as PXA


def main():
    start_time = time()
    xplora = PXA.PyXploraApi("+49", "1234567890", "PASSWORD", "de-DE", "Europe/Berlin")
    xplora.init()
    while True:
        print(xplora.getWatchChatsRaw("011012345678901234567890123456", 0, 1)
        sleep(30)
```

for me it will be updated after time has expired.
